- src/components/Register.js
> añade sección de register

- src/components/Home.js
@JaviGandarillas  y @paolandre  Ahí van los botones del Home
> Agrega botones de inicio de sesión y register al Home

- src/components/Home.js
- src/components/Login.js
- src/components/Register.js
- src/main.js
@JaviGandarillas y @paolandre !!
Hago el pull requests, pero sí fíjense bien si no hubo algún error de mi parte.
> agrega función onNagivate y la pasa por parámetro, pero no la exporta

- src/components/Login.js
Hola @JaviGandarillas y @Natalia392 
Esto es el OnNavigate solucionado 👯
> OnNavigate solucionado

- src/components/Register.js
> añade p contraseña

- src/components/Home.js
- src/components/Register.js
> modifica sección de register

- src/components/Home.js
- src/components/Login.js
- src/components/Register.js
- src/main.js
> Modifica el login, creando el form para hacer inicio de sesión

- src/app/firebase.js
- src/components/Register.js
> autentificando emails con asyn await

- src/components/Register.js
> Añade iniciar sesión con google, pendiente terminar errores

- src/components/Register.js
> restringe espacios en la contraseña

- src/components/Home.js
- src/components/Login.js
- src/components/Register.js
- src/components/Wall.js
- src/main.js
- src/style.css
> añade titulo comunidad del libro y algunos ajustes css

- src/components/Login.js
- src/components/Register.js
Les dejo la apertura al wall @paolandre @JaviGandarillas
> añade navegación desde inicio de sesión a wall

- src/components/Wall.js
- src/style.css
> Estructura de los posts 

- src/app/firebase.js
- src/components/Home.js
- src/components/Login.js
- src/components/Register.js
- src/components/Wall.js
- src/lib/index.js
> crea función para postear, pero tiene error de permisos

- src/components/Login.js
- src/components/Register.js
- src/components/Wall.js
- src/lib/index.js
@paolandre @JaviGandarillas 
Ahí va, revisad.
> agrega funcionalidad para crear colecciones de posts en firebase

- src/components/Login.js
- src/components/Register.js
- src/lib/index.js
@JaviGandarillas @paolandre 
Con las validaciones.
> Agrega validación de campos ingresado en registro y login

- src/components/Home.js
- src/components/Login.js
- src/components/Register.js
> ordena creación de la estructura html

- src/components/Register.js
- src/lib/index.js
@paolandre @JaviGandarillas 
Arreglado el asyn await
> Agrega el async await necesario en funciones puras

- src/components/Wall.js
- src/style.css
> La comunidad del Libro Historia de Usuario 1 y 2

- src/components/Wall.js
- src/lib/index.js
> muestra en consola los objetos de los post registrados en firebase

- package.json
- src/components/Wall.js
- src/lib/index.js
> Finalmente los posts se pueden mostrar y mantener

- src/components/Wall.js
- src/style.css
> Cambios en el CSS de la ventana del wall

- src/components/Wall.js
- src/lib/index.js
> toma la fecha pero no orden aún (pese a tener orderBy)

- src/components/Wall.js
- src/lib/index.js
> Ya se puede ver la hora y fecha en la consola

- src/components/Wall.js
- src/lib/index.js
> función de likes con .then para cambiar corazón

- src/components/Wall.js
- src/components/modal.js
- src/lib/index.js
- src/style.css
> agrega funcionalidad para eliminar posts con ventana modal

- src/components/Wall.js
- src/lib/index.js
> Probando función de like

- src/lib/index.js
- src/style.css
- test/index.spec.js
test a ourCreateUserWithEmailAndPassword
@JaviGandarillas @paolandre
> Añade ajustes de estilo al input de posts y primeros tests 

- src/components/Wall.js
- src/lib/index.js
- test/index.spec.js
> tests de ourcreate, oursignin, signInWithGoogle

- src/lib/index.js
- test/index.spec.js
> tests de ourCreate, ourSign, signinwithgoogle, createPost listos

- test/index.spec.js
> test de createPost modificado

- src/components/Wall.js
- src/components/modal.js
- src/style.css
> Arregla textarea para la mayoría de dispositivos

- src/style.css
> reajusta textarea

- src/components/Login.js
- src/components/Register.js
- src/components/Wall.js
- src/lib/index.js
> Agrega el usuario al localstorage

- src/style.css
@paolandre @Natalia392 @JaviGandarillas
> añade padding perdido en el internet

- src/components/Home.js
- src/components/Wall.js
- src/components/modal.js
- src/lib/index.js
- src/main.js
- src/style.css
- test/index.spec.js
> Agrega documentación a index.js y a wall

- src/components/Home.js
> añade condición de existencia de usuario en home

- src/components/Home.js
- src/components/Login.js
- src/components/Register.js
- src/components/Wall.js
- src/main.js
Se agrega la funcionalidad de onAuthStateChanged desde el ruteo en main.js. Esto verifica si hay usuario y lo manda a la ruta correspondiente.
@JaviGandarillas @paolandre
> agrega onAuthStateChanged 
